version: '3'
services:
  app:
    container_name: app
    restart: always
    build: ./app
    env_file:
          - ./app/.env
    ports:
      - '3000:3000'
    volumes:
      - './app/:/wrk'
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: 'mongo:3.6.2'
    volumes:
      - 'db-data:/var/lib/mongodb'
    ports:
      - '27017:27017'
volumes:
  db-data:
    driver: local
